### ISSUE TITLE
Adicionar à classe Inimigos, o inimigo Esqueleto

### ISSUE THREAD

**Issue by vinilopes03** [jorgetbruno/roomforchange#6]
- Segue o personagem principal
- Muita vida
- Lento

**Comment by adryanoalf** [comment]
Esqueleto adicionado, com muita vida, lento e segue o personagem.

Bug: Mesmo que o zombie.

**Comment by adryanoalf** [comment]
Alinhamento de imagem corrigido.

**Comment by adryanoalf** [comment]
Bug de animação corrigido.
