### ISSUE TITLE
Adicionar à classe Inimigos, o inimigo Fantasma

### ISSUE THREAD

**Issue by vinilopes03** [jorgetbruno/roomforchange#7]
- Segue o personagem 
- ignora colisão 
- possui pouca vida  
- fica lento se o personagem olhar para ele

**Comment by adryanoalf** [comment]
Fantasma adicionado, segue o personagem se estiver próximo, possui pouca vida.

Falta: Ignorar colisão e ficar lento se o personagem olhar pra ele.

**Comment by adryanoalf** [comment]
Fastasma agora ignora colisão.

**Comment by adryanoalf** [comment]
Alinhamento de imagem corrigido.
