### ISSUE TITLE
Adicionar à classe Inimigos, o inimigo Zombie

### ISSUE THREAD

**Issue by vinilopes03** [jorgetbruno/roomforchange#8]
- Segue o personagem 
- pouca vida
- É rápido.

**Comment by adryanoalf** [comment]
Zombie adicionado com pouca vida, rápido e segue o personagem.

Bugs: Animação para cima e baixo podem bugar.

**Comment by adryanoalf** [comment]
Alinhamento de imagem corrigido.

**Comment by adryanoalf** [comment]
Bug de animação corrigido.
